In [330]:
import pandas as pd
import numpy as np

In [331]:
boston = pd.read_csv('https://andybek.com/pandas-marathon')

In [332]:
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           1000 non-null   object
 1   Age            1000 non-null   int64
 2   M/F            1000 non-null   object
 3   City           1000 non-null   object
 4   State          807 non-null    object
 5   Country        1000 non-null   object
 6   Official Time  1000 non-null   object
 7   Overall        1000 non-null   int64
 8   Gender         1000 non-null   int64
 9   Years Ran      315 non-null    object
dtypes: int64(3), object(7)
memory usage: 78.3+ KB

# String Operations in Pandas

In [333]:
boston.City

0           Keringet
1           Portland
2       Machida-City
3      Mammoth Lakes
4           Marakwet
           ...
995    North Andover
996          Raleigh
997        Arlington
998          Danbury
999         Santa Fe
Name: City, Length: 1000, dtype: object

In [334]:
boston.City.str.capitalize()

0           Keringet
1           Portland
2       Machida-city
3      Mammoth lakes
4           Marakwet
           ...
995    North andover
996          Raleigh
997        Arlington
998          Danbury
999         Santa fe
Name: City, Length: 1000, dtype: object

In [335]:
#Find a substring within a text column in Pandas
boston.City.str.find('ston').value_counts() # Returns the position for the first occurrence of the substring

City
-1    962
 2     22
 3     11
 4      3
 8      1
 6      1
Name: count, dtype: int64

In [336]:
boston.City.str.contains('ston').value_counts() #Returns a boolean --> to indicate the presence of the substring
boston[boston.City.str.contains('ston')]

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran
19,"Harvey, Brian",29,M,Boston,MA,USA,2:20:18,20,20,NaN
27,"Ashe, Eric",28,M,Boston,MA,USA,2:23:26,28,25,NaN
31,"Ayr, Jason M.",29,M,Allston,MA,USA,2:24:49,32,29,2015:2016
65,"Gilmore, Peter",27,M,Boston,MA,USA,2:31:13,66,59,NaN
82,"Klecker, Jack R",25,M,Boston,MA,USA,2:33:12,83,74,2015
124,"Cater-Cyker, Zach",32,M,Houston,TX,USA,2:36:48,125,109,2015:2016
164,"Yitref, Gedion",27,M,Evanston,IL,USA,2:38:59,165,145,2015:2016
169,"Deeg, Thomas J",36,M,Marstons Mills,MA,USA,2:39:16,170,150,2015:2016
174,"Pierce, Clayton J.",25,M,Boston,MA,USA,2:39:32,175,155,2015:2016
180,"Zhou, Fan",28,M,Boston,MA,USA,2:39:40,181,161,2015:2016
182,"Battoo, Christopher",29,M,Boston,MA,USA,2:39:54,183,163,2015:2016
199,"Guzick, William F",28,M,Boston,MA,USA,2:40:43,200,178,NaN
253,"Fitzpatrick, Michael J",39,M,Boston,MA,USA,2:42:56,254,230,2016
314,"Thomas, Malcolm",36,M,Boston,MA,USA,2:44:32,315,288,2015
345,"Scoville, Morgan B.",34,M,Houston,TX,USA,2:45:24,346,319,2015:2016
398,"Cyganik, Jonathan",24,M,Boston,MA,USA,2:46:31,399,369,NaN
404,"Orlando, Matthew P",24,M,Boston,MA,USA,2:46:39,405,375,NaN
428,"Groudle, Alan M",33,M,Lewiston,ME,USA,2:47:14,429,398,NaN
454,"Pires, Corey",21,M,North Easton,MA,USA,2:47:36,455,423,2016
518,"Comite, Daniel O.",28,M,Charleston,SC,USA,2:49:02,519,482,NaN
540,"Richter, Peter W Sr.",44,M,Winston Salem,NC,USA,2:49:24,541,504,NaN
555,"Hansen, Ryan P",29,M,Boston,MA,USA,2:49:36,556,518,NaN
558,"Mcdonough, Bobby",24,M,Allston,MA,USA,2:49:38,559,521,NaN
560,"Keshian, Gregory",30,M,Boston,MA,USA,2:49:39,561,523,2015:2016
651,"Cantini, Adam",25,M,Houston,TX,USA,2:51:16,652,612,2015:2016
675,"Kariolis, Vasilis S",28,M,Boston,MA,USA,2:51:43,676,636,2015
705,"Smith, David W. Jr.",26,M,Houston,TX,USA,2:52:10,706,665,NaN
723,"Newhouse, James B",24,M,Boston,MA,USA,2:52:30,724,681,NaN
770,"Rutt, Matthew",26,M,Kingston,PA,USA,2:53:04,771,726,NaN
795,"Phillips, Michael T",33,M,Boston,MA,USA,2:53:31,796,750,2015
832,"Kenny, Ryan F",37,M,Boston,MA,USA,2:54:04,833,786,NaN
845,"Bishop, Nathan",36,M,Houston,TX,USA,2:54:17,846,797,NaN
907,"Gerald, Jean-Philippe",33,M,Boston,MA,USA,2:55:03,908,857,NaN
911,"Sanderson, Samuel",39,M,Houston,TX,USA,2:55:07,912,861,NaN
914,"Wendel, Nicholas",25,M,Boston,MA,USA,2:55:07,915,864,NaN
918,"King, David R.",43,M,Boston,MA,USA,2:55:10,919,868,NaN
927,"Grinstead, Tyler J",25,M,Houston,TX,USA,2:55:14,928,877,NaN
992,"Gavin, Timothy V.",41,M,Weston,MA,USA,2:56:04,993,937,NaN

In [337]:
#stripping whitespaces
boston.Name = boston.Name.str.strip()

In [338]:
boston.sample(10)

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran
775,"Yang, Shizhong",35,M,West Hartford,CT,USA,2:53:06,776,731,2015:2016
353,"Vanderven, Ian",26,M,Skaneateles,NY,USA,2:45:35,354,327,NaN
519,"Schrandt, Erik J",20,M,Madison,WI,USA,2:49:02,520,483,NaN
799,"Cabral, Manuel",42,M,Laval,QC,CAN,2:53:34,800,754,2015:2016
370,"Dorval, Guy",56,M,Quebec,QC,CAN,2:45:53,371,342,2016
226,"Aldrich, Micah J",27,M,Indianapolis,IN,USA,2:42:02,227,204,NaN
282,"Whitlow, Dustin M",30,M,Arlington,VA,USA,2:43:47,283,257,NaN
938,"Dimbleby, Peter J.",42,M,Walsall,NaN,GBR,2:55:23,939,888,NaN
868,"Garvey, Thomas G IV",32,M,New York,NY,USA,2:54:34,869,820,2015:2016
130,"Mcmillan, Erik D",19,M,Usaf Academy,CO,USA,2:37:15,131,115,NaN

In [339]:
boston.loc[909,'Name']

'Qin, Zhenning'

In [340]:
boston.Name.iloc[570]

'Hoedl, Hanspeter'

# String splitting and concatenation

In [341]:
#Split the name column in the dataframe into first and last names

In [342]:
df = boston.Name.str.split(', ',expand=True).rename(columns={0:'First Name',1:'Last Name'})

In [343]:
#Concatenating two dataframes
df1 = pd.concat([boston,df],axis=1)

In [344]:
df1.sample(5)

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran,First Name,Last Name
864,"Jungkans, Chris W.",55,M,Salem,WI,USA,2:54:29,865,816,NaN,Jungkans,Chris W.
36,"Vangampleare, Stephen",26,M,Colorado Springs,CO,USA,2:25:35,37,33,2015:2016,Vangampleare,Stephen
633,"Chapman, Stephen P",34,M,Ottawa,ON,CAN,2:50:56,634,594,2015,Chapman,Stephen P
318,"Conklin, Eric M",28,M,Cornelius,NC,USA,2:44:34,319,292,NaN,Conklin,Eric M
692,"Dehring, Michael J.",46,M,Cincinnati,OH,USA,2:51:57,693,652,NaN,Dehring,Michael J.

In [345]:
#Setting with Enlargement
df[['First Name','Last Name']] = boston.Name.str.split(', ',expand=True)

In [346]:
df.sample(5)

         First Name     Last Name
806           Lovig    Christy L.
332           Krall         David
684           Hardy     Sebastien
810  Ferreira Filho  Guilherme A.
973        Kingston        Hudson

In [347]:
#To get the first name only

In [348]:
boston.Name.str.split(', ').str.get(0)

0           Kirui
1            Rupp
2           Osako
3          Biwott
4          Chebet
          ...
995        Larosa
996    Williamson
997         Mccue
998        Larosa
999       Sanchez
Name: Name, Length: 1000, dtype: object

In [349]:
boston['First Name'] = boston.Name.str.split(', ').str.get(0)
boston['Last Name'] = boston.Name.str.split(', ').str.get(1)

In [350]:
boston.sample(5)

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran,First Name,Last Name
661,"O'Donoghue, Graham",38,M,Washington,DC,USA,2:51:26,662,622,NaN,O'Donoghue,Graham
712,"Delia, Ben",34,M,Lancaster,PA,USA,2:52:17,713,671,2016,Delia,Ben
50,"Tropf, Jordan",25,M,Baltimore,MD,USA,2:28:43,51,46,NaN,Tropf,Jordan
275,"Franken, Christiaan",35,M,Amsterdam,NaN,NED,2:43:35,276,251,NaN,Franken,Christiaan
721,"Landry, Paul",46,M,Golden,CO,USA,2:52:28,722,679,2015:2016,Landry,Paul

In [351]:
#concatenating strings

In [352]:
boston['M/F'].str.cat(boston['Age'].astype(str),sep='-')

0      M-24
1      M-30
2      M-25
3      M-32
4      M-31
       ...
995    M-38
996    M-43
997    M-40
998    M-35
999    M-35
Name: M/F, Length: 1000, dtype: object

# Skill Challenge

In [353]:
#How many runners in the dataframe has James as the last name

In [354]:
boston.loc[boston.Name.str.split(', ').str.get(1) == 'James'].index

Index([243, 574, 650, 923, 976], dtype='int64')

In [355]:
boston.Name[boston.loc[boston.Name.str.split(', ').str.get(1) == 'James'].index]

243         Lloyd, James
574      Onigkeit, James
650    O'Sullivan, James
923          Baek, James
976       Blowers, James
Name: Name, dtype: object

In [356]:
#Split the city names by '-' and create a dataframe with each split component of the split name. Assign the dataframe to city_parts.

In [357]:
city_parts = boston.City.str.split('-',expand=True,n=1)

In [358]:
city_parts

                 0     1
0         Keringet  None
1         Portland  None
2          Machida  City
3    Mammoth Lakes  None
4         Marakwet  None
..             ...   ...
995  North Andover  None
996        Raleigh  None
997      Arlington  None
998        Danbury  None
999       Santa Fe  None

[1000 rows x 2 columns]

In [359]:
#Which cities have more than one component?

In [360]:
boston[city_parts.count(axis=1) > 1][['City','Country']]

                           City Country
2                  Machida-City     JPN
35               Sao Paulo - Sp     BRA
188                Baie-St-Paul     CAN
201          Houghton-Le-Spring     GBR
371        Boulogne-Billancourt     FRA
420                  Mont-Royal     CAN
585              Gif-Sur-Yvette     FRA
615      Fossambault-Sur-Le-Lac     CAN
724       Wiesbaden-Breckenheim     GER
727                  Saint-Tite     CAN
794                 Marica - Rj     BRA
820  Sainte-Catherine-De-Hatley     CAN
830                  Pont-Rouge     CAN

# String slicing in Pandas

In [361]:
boston.sample(5)

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran,First Name,Last Name
280,"Gibson, Audrey L.",24,F,San Francisco,CA,USA,2:43:44,281,26,NaN,Gibson,Audrey L.
224,"Rouse, Matthew",31,M,San Diego,CA,USA,2:41:58,225,202,NaN,Rouse,Matthew
686,"Waxman, Marc",44,M,Wrentham,MA,USA,2:51:50,687,646,2015,Waxman,Marc
114,"McMahan, Dot",40,F,Oakland Township,MI,USA,2:36:28,115,14,NaN,McMahan,Dot
601,"Kortman, John",23,M,Indianapolis,IN,USA,2:50:19,602,563,NaN,Kortman,John

In [362]:
boston.Country.str[:2]

0      KE
1      US
2      JP
3      US
4      KE
       ..
995    US
996    US
997    US
998    US
999    US
Name: Country, Length: 1000, dtype: object

In [363]:
boston.Country.str[-2:]

0      EN
1      SA
2      PN
3      SA
4      EN
       ..
995    SA
996    SA
997    SA
998    SA
999    SA
Name: Country, Length: 1000, dtype: object

In [364]:
boston_time = boston.loc[:,'Official Time']

In [365]:
pd.to_datetime(boston_time, format='%H:%M:%S').dt.time

0      02:09:37
1      02:09:58
2      02:10:28
3      02:12:08
4      02:12:35
         ...
995    02:56:06
996    02:56:06
997    02:56:06
998    02:56:07
999    02:56:08
Name: Official Time, Length: 1000, dtype: object

In [366]:
type(boston_time)

pandas.core.series.Series

In [367]:
boston_time.astype('datetime64[ns]')

0     2025-06-15 02:09:37
1     2025-06-15 02:09:58
2     2025-06-15 02:10:28
3     2025-06-15 02:12:08
4     2025-06-15 02:12:35
              ...
995   2025-06-15 02:56:06
996   2025-06-15 02:56:06
997   2025-06-15 02:56:06
998   2025-06-15 02:56:07
999   2025-06-15 02:56:08
Name: Official Time, Length: 1000, dtype: datetime64[ns]

In [368]:
boston_time_only = pd.to_datetime(boston_time, format='%H:%M:%S').dt.time
display(boston_time_only)

0      02:09:37
1      02:09:58
2      02:10:28
3      02:12:08
4      02:12:35
         ...
995    02:56:06
996    02:56:06
997    02:56:06
998    02:56:07
999    02:56:08
Name: Official Time, Length: 1000, dtype: object

In [369]:
boston['Official Time Delta'] = pd.to_datetime(boston['Official Time'], format='%H:%M:%S') - pd.to_datetime('00:00:00', format='%H:%M:%S')
display(boston[['Official Time', 'Official Time Delta']].head())

  Official Time Official Time Delta
0       2:09:37     0 days 02:09:37
1       2:09:58     0 days 02:09:58
2       2:10:28     0 days 02:10:28
3       2:12:08     0 days 02:12:08
4       2:12:35     0 days 02:12:35

# Using get_dummies() method

In [370]:
#Find runners who have participated in at least one of the prior to years

In [371]:
boston.head()

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran,First Name,Last Name,Official Time Delta
0,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,2:09:37,1,1,NaN,Kirui,Geoffrey,0 days 02:09:37
1,"Rupp, Galen",30,M,Portland,OR,USA,2:09:58,2,2,NaN,Rupp,Galen,0 days 02:09:58
2,"Osako, Suguru",25,M,Machida-City,NaN,JPN,2:10:28,3,3,NaN,Osako,Suguru,0 days 02:10:28
3,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,USA,2:12:08,4,4,NaN,Biwott,Shadrack,0 days 02:12:08
4,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,2:12:35,5,5,2015,Chebet,Wilson,0 days 02:12:35

In [372]:
boston.loc[boston['Years Ran'].notnull()]

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran,First Name,Last Name,Official Time Delta
4,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,2:12:35,5,5,2015,Chebet,Wilson,0 days 02:12:35
12,"Keflezighi, Meb",41,M,San Diego,CA,USA,2:17:00,13,13,2015,Keflezighi,Meb,0 days 02:17:00
13,"Nyasango, Cutbert",34,M,Harara,NaN,ZIM,2:17:40,14,14,2016,Nyasango,Cutbert,0 days 02:17:40
14,"Korir, Wesley",34,M,Kitale,NaN,KEN,2:18:14,15,15,2015:2016,Korir,Wesley,0 days 02:18:14
29,"Maravilla, Jorge",39,M,Mill Valley,CA,USA,2:24:27,30,27,2016,Maravilla,Jorge,0 days 02:24:27
...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,"Bretz, Virgil",44,M,Mt. Kisco,NY,USA,2:56:02,987,931,2015:2016,Bretz,Virgil,0 days 02:56:02
987,"Cucuzzella, Mark",50,M,Shepherdstown,WV,USA,2:56:03,988,932,2016,Cucuzzella,Mark,0 days 02:56:03
988,"Carron, John B",46,M,Irvington,NY,USA,2:56:03,989,933,2016,Carron,John B,0 days 02:56:03
995,"Larosa, Mark",38,M,North Andover,MA,USA,2:56:06,996,940,2015:2016,Larosa,Mark,0 days 02:56:06
996,"Williamson, Jerry A",43,M,Raleigh,NC,USA,2:56:06,997,941,2015,Williamson,Jerry A,0 days 02:56:06

In [373]:
#use get_dummies method to split the Years Ran in two separate columns - convert categorical columns to indicator/ boolean columns

In [374]:
df = boston['Years Ran'].str.get_dummies(sep=':')

In [375]:
df.head()

   2015  2016
0     0     0
1     0     0
2     0     0
3     0     0
4     1     0

In [376]:
#Insert these columns in the dataframe

In [377]:
boston.columns.get_loc('Years Ran')

9

In [378]:
boston.insert(boston.columns.get_loc('Years Ran'), 'Ran 2015',df['2015'])

In [379]:
boston.insert(boston.columns.get_loc('Years Ran'), 'Ran 2016',df['2016'])

In [380]:
boston.head()

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Ran 2015,Ran 2016,Years Ran,First Name,Last Name,Official Time Delta
0,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,2:09:37,1,1,0,0,NaN,Kirui,Geoffrey,0 days 02:09:37
1,"Rupp, Galen",30,M,Portland,OR,USA,2:09:58,2,2,0,0,NaN,Rupp,Galen,0 days 02:09:58
2,"Osako, Suguru",25,M,Machida-City,NaN,JPN,2:10:28,3,3,0,0,NaN,Osako,Suguru,0 days 02:10:28
3,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,USA,2:12:08,4,4,0,0,NaN,Biwott,Shadrack,0 days 02:12:08
4,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,2:12:35,5,5,1,0,2015,Chebet,Wilson,0 days 02:12:35

In [381]:
boston[(boston['Ran 2015'] == 1) | (boston['Ran 2016'] == 1)]

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Ran 2015,Ran 2016,Years Ran,First Name,Last Name,Official Time Delta
4,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,2:12:35,5,5,1,0,2015,Chebet,Wilson,0 days 02:12:35
12,"Keflezighi, Meb",41,M,San Diego,CA,USA,2:17:00,13,13,1,0,2015,Keflezighi,Meb,0 days 02:17:00
13,"Nyasango, Cutbert",34,M,Harara,NaN,ZIM,2:17:40,14,14,0,1,2016,Nyasango,Cutbert,0 days 02:17:40
14,"Korir, Wesley",34,M,Kitale,NaN,KEN,2:18:14,15,15,1,1,2015:2016,Korir,Wesley,0 days 02:18:14
29,"Maravilla, Jorge",39,M,Mill Valley,CA,USA,2:24:27,30,27,0,1,2016,Maravilla,Jorge,0 days 02:24:27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,"Bretz, Virgil",44,M,Mt. Kisco,NY,USA,2:56:02,987,931,1,1,2015:2016,Bretz,Virgil,0 days 02:56:02
987,"Cucuzzella, Mark",50,M,Shepherdstown,WV,USA,2:56:03,988,932,0,1,2016,Cucuzzella,Mark,0 days 02:56:03
988,"Carron, John B",46,M,Irvington,NY,USA,2:56:03,989,933,0,1,2016,Carron,John B,0 days 02:56:03
995,"Larosa, Mark",38,M,North Andover,MA,USA,2:56:06,996,940,1,1,2015:2016,Larosa,Mark,0 days 02:56:06
996,"Williamson, Jerry A",43,M,Raleigh,NC,USA,2:56:06,997,941,1,0,2015,Williamson,Jerry A,0 days 02:56:06

In [382]:
boston.loc[boston['Ran 2016'] == 1].Name

13     Nyasango, Cutbert
14         Korir, Wesley
29      Maravilla, Jorge
30      Ornelas, Zachary
31         Ayr, Jason M.
             ...
983        Wong, Ka Ming
986        Bretz, Virgil
987     Cucuzzella, Mark
988       Carron, John B
995         Larosa, Mark
Name: Name, Length: 249, dtype: object

# Text Replacements

In [383]:
#Replace M in M/F column by Male and F by Female

In [384]:
boston['M/F'].str.replace('M','Male')

0      Male
1      Male
2      Male
3      Male
4      Male
       ...
995    Male
996    Male
997    Male
998    Male
999    Male
Name: M/F, Length: 1000, dtype: object

In [385]:
boston['M/F'] = boston['M/F'].replace(['M','F'],['Male','Female'])

In [386]:
boston.sample()

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Ran 2015,Ran 2016,Years Ran,First Name,Last Name,Official Time Delta
533,"Fukuchi, Yoshinori",46,Male,Tokyo,NaN,JPN,2:49:17,534,497,1,1,2015:2016,Fukuchi,Yoshinori,0 days 02:49:17

# Pandas str contains(), split() and replace() with Regex

In [387]:
#Isolate runners whose first name is Will

In [388]:
boston.Name[boston.Name.str.contains(r',\s[wW]ill$',regex=True)]

456      Cunha, Will
526    Swenson, Will
835     Vargas, Will
892     Rivera, Will
Name: Name, dtype: object

In [389]:
boston.Name[boston.Name.str.contains(r',\s[wW]ill\b',regex=True)]

456      Cunha, Will
526    Swenson, Will
835     Vargas, Will
892     Rivera, Will
Name: Name, dtype: object

In [390]:
boston.iat[526,0]+= ' J.'

In [391]:
boston.Name[boston.Name.str.contains(r',\s[wW]ill\b',regex=True)]

456         Cunha, Will
526    Swenson, Will J.
835        Vargas, Will
892        Rivera, Will
Name: Name, dtype: object

In [392]:
#Using string split with Regex
boston.Name.str.split(r'\s',expand=True,regex=True)

               0         1     2     3     4
0         Kirui,  Geoffrey  None  None  None
1          Rupp,     Galen  None  None  None
2         Osako,    Suguru  None  None  None
3        Biwott,  Shadrack  None  None  None
4        Chebet,    Wilson  None  None  None
..           ...       ...   ...   ...   ...
995      Larosa,      Mark  None  None  None
996  Williamson,     Jerry     A  None  None
997       Mccue,    Daniel     T  None  None
998      Larosa,      John  None  None  None
999     Sanchez,       Sam     R  None  None

[1000 rows x 5 columns]

In [393]:
#Using replace with Regex

In [394]:
boston['Official Time'].sample(5)

956    2:55:39
422    2:47:03
286    2:43:52
741    2:52:46
751    2:52:52
Name: Official Time, dtype: object

In [395]:
boston['Official Time'].str.replace(r'(\d+):(\d+):(\d+)',r'\1 hrs. \2 min. and \3 sec.',regex=True)

0      2 hrs. 09 min. and 37 sec.
1      2 hrs. 09 min. and 58 sec.
2      2 hrs. 10 min. and 28 sec.
3      2 hrs. 12 min. and 08 sec.
4      2 hrs. 12 min. and 35 sec.
                  ...
995    2 hrs. 56 min. and 06 sec.
996    2 hrs. 56 min. and 06 sec.
997    2 hrs. 56 min. and 06 sec.
998    2 hrs. 56 min. and 07 sec.
999    2 hrs. 56 min. and 08 sec.
Name: Official Time, Length: 1000, dtype: object

In [413]:
boston[boston['Ran 2016']==1]['Official Time']

13     2:17:40
14     2:18:14
29     2:24:27
30     2:24:40
31     2:24:49
        ...
983    2:56:00
986    2:56:02
987    2:56:03
988    2:56:03
995    2:56:06
Name: Official Time, Length: 249, dtype: object

# Skill Challenge

In [453]:
del final_times

In [454]:
#Split the Official Time into three separate columns. Store the dataframe in a varaible called final_times.

In [455]:
final_times = boston['Official Time'].str.split(':',expand=True)

In [456]:
final_times.head()

   0   1   2
0  2  09  37
1  2  09  58
2  2  10  28
3  2  12  08
4  2  12  35

In [457]:
#In the final_times dataframe create a new column called total that contains the total in seconds. Add the column to the boston dataframe

In [458]:
final_times = final_times.astype(int)

In [459]:
final_times

     0   1   2
0    2   9  37
1    2   9  58
2    2  10  28
3    2  12   8
4    2  12  35
..  ..  ..  ..
995  2  56   6
996  2  56   6
997  2  56   6
998  2  56   7
999  2  56   8

[1000 rows x 3 columns]

In [460]:
final_times['total'] = final_times.apply(lambda x: x.iat[0]*60*60 + x.iat[1]*60 + x.iat[2],axis=1)

In [461]:
final_times.total.notnull().value_counts()

total
True    1000
Name: count, dtype: int64

In [462]:
final_times.head()

   0   1   2  total
0  2   9  37   7777
1  2   9  58   7798
2  2  10  28   7828
3  2  12   8   7928
4  2  12  35   7955

In [463]:
boston[boston['Ran 2016']==1]

,Name,Age,M/F,City,State,Country,Official Time,total,Overall,Gender,Ran 2015,Ran 2016,Years Ran,First Name,Last Name,Official Time Delta
13,"Nyasango, Cutbert",34,Male,Harara,NaN,ZIM,2:17:40,NaN,14,14,0,1,2016,Nyasango,Cutbert,0 days 02:17:40
14,"Korir, Wesley",34,Male,Kitale,NaN,KEN,2:18:14,NaN,15,15,1,1,2015:2016,Korir,Wesley,0 days 02:18:14
29,"Maravilla, Jorge",39,Male,Mill Valley,CA,USA,2:24:27,NaN,30,27,0,1,2016,Maravilla,Jorge,0 days 02:24:27
30,"Ornelas, Zachary",25,Male,Ann Arbor,MI,USA,2:24:40,NaN,31,28,1,1,2015:2016,Ornelas,Zachary,0 days 02:24:40
31,"Ayr, Jason M.",29,Male,Allston,MA,USA,2:24:49,NaN,32,29,1,1,2015:2016,Ayr,Jason M.,0 days 02:24:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,"Wong, Ka Ming",36,Male,Hong Kong,NaN,HKG,2:56:00,NaN,984,928,0,1,2016,Wong,Ka Ming,0 days 02:56:00
986,"Bretz, Virgil",44,Male,Mt. Kisco,NY,USA,2:56:02,NaN,987,931,1,1,2015:2016,Bretz,Virgil,0 days 02:56:02
987,"Cucuzzella, Mark",50,Male,Shepherdstown,WV,USA,2:56:03,NaN,988,932,0,1,2016,Cucuzzella,Mark,0 days 02:56:03
988,"Carron, John B",46,Male,Irvington,NY,USA,2:56:03,NaN,989,933,0,1,2016,Carron,John B,0 days 02:56:03
995,"Larosa, Mark",38,Male,North Andover,MA,USA,2:56:06,NaN,996,940,1,1,2015:2016,Larosa,Mark,0 days 02:56:06

In [464]:
boston.head()

,Name,Age,M/F,City,State,Country,Official Time,total,Overall,Gender,Ran 2015,Ran 2016,Years Ran,First Name,Last Name,Official Time Delta
0,"Kirui, Geoffrey",24,Male,Keringet,NaN,KEN,2:09:37,7322.0,1,1,0,0,NaN,Kirui,Geoffrey,0 days 02:09:37
1,"Rupp, Galen",30,Male,Portland,OR,USA,2:09:58,32950.0,2,2,0,0,NaN,Rupp,Galen,0 days 02:09:58
2,"Osako, Suguru",25,Male,Machida-City,NaN,JPN,2:10:28,136708.0,3,3,0,0,NaN,Osako,Suguru,0 days 02:10:28
3,"Biwott, Shadrack",32,Male,Mammoth Lakes,CA,USA,2:12:08,NaN,4,4,0,0,NaN,Biwott,Shadrack,0 days 02:12:08
4,"Chebet, Wilson",31,Male,Marakwet,NaN,KEN,2:12:35,NaN,5,5,1,0,2015,Chebet,Wilson,0 days 02:12:35

In [406]:
final_times.head()

   0   1   2     total
0  2   9  37    7322.0
1  2   9  58   32950.0
2  2  10  28  136708.0
3  2  12   8       NaN
4  2  12  35       NaN

In [465]:
boston.drop('total',axis=1,inplace=True)

In [466]:
boston[boston['Ran 2016']==1]['Official Time'].notnull().value_counts()

Official Time
True    249
Name: count, dtype: int64

In [467]:
boston.insert(boston.columns.get_loc('Official Time')+1, 'total',final_times['total'].values)

In [468]:
boston.head()

,Name,Age,M/F,City,State,Country,Official Time,total,Overall,Gender,Ran 2015,Ran 2016,Years Ran,First Name,Last Name,Official Time Delta
0,"Kirui, Geoffrey",24,Male,Keringet,NaN,KEN,2:09:37,7777,1,1,0,0,NaN,Kirui,Geoffrey,0 days 02:09:37
1,"Rupp, Galen",30,Male,Portland,OR,USA,2:09:58,7798,2,2,0,0,NaN,Rupp,Galen,0 days 02:09:58
2,"Osako, Suguru",25,Male,Machida-City,NaN,JPN,2:10:28,7828,3,3,0,0,NaN,Osako,Suguru,0 days 02:10:28
3,"Biwott, Shadrack",32,Male,Mammoth Lakes,CA,USA,2:12:08,7928,4,4,0,0,NaN,Biwott,Shadrack,0 days 02:12:08
4,"Chebet, Wilson",31,Male,Marakwet,NaN,KEN,2:12:35,7955,5,5,1,0,2015,Chebet,Wilson,0 days 02:12:35

In [469]:
boston[boston['Ran 2016']==1].total.notnull().value_counts()

total
True    249
Name: count, dtype: int64

In [470]:
#Do the runners in boston dataframe who ran in 2016 has a higher or lower average time?

In [500]:
print('Average time for runners who ran in 2016:',str(pd.to_timedelta(boston[boston['Ran 2016']==1].get('total').mean(),unit='s')).split()[-1])
print('Average time for runners who did not run in 2016:',str(pd.to_timedelta(boston[boston['Ran 2016']==0].get('total').mean(),unit='s')).split()[-1])

Average time for runners who ran in 2016: 02:47:23.120481928
Average time for runners who did not run in 2016: 02:46:06.195739015

In [487]:
hhmmss = str(pd.to_timedelta(10043.12048192771,unit='s'))

In [488]:
hhmmss

'0 days 02:47:23.120481928'

In [490]:
hhmmss.split()[-1]

'02:47:23.120481928'