In [1]:
import pandas as pd
import numpy as np

In [2]:
sat_url = 'https://andybek.com/pandas-sat'

In [3]:
sat = pd.read_csv(sat_url)

In [4]:
sat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   School Name         1125 non-null   object
 1   Borough             1125 non-null   object
 2   Student Enrollment  1125 non-null   int64
 3   Percent Tested      1125 non-null   object
 4   SAT Section         1125 non-null   object
 5   Score               1125 non-null   int64
dtypes: int64(2), object(4)
memory usage: 52.9+ KB

In [5]:
sat['Percent Tested'] = sat['Percent Tested'].replace('%', '', regex=True).astype('float')

In [6]:
sat

,School Name,Borough,Student Enrollment,Percent Tested,SAT Section,Score
0,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Math,459
1,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Reading,453
2,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Writing,447
3,Abraham Lincoln High School,Brooklyn,2341,54.9,Math,441
4,Abraham Lincoln High School,Brooklyn,2341,54.9,Reading,422
...,...,...,...,...,...,...
1120,Young Women's Leadership School in Astoria,Queens,572,100.0,Reading,464
1121,Young Women's Leadership School in Astoria,Queens,572,100.0,Writing,477
1122,Young Women's Leadership School in Queens,Queens,557,90.4,Math,415
1123,Young Women's Leadership School in Queens,Queens,557,90.4,Reading,420
1124,Young Women's Leadership School in Queens,Queens,557,90.4,Writing,433

# Pivoting Dataframe

In [7]:
#Reshaping the data using chained unstack
#1. Setting the School Name, Borough and SAT Section as Indices as a Multiindiex Dataframe
#2. Unpacking the SAT Section so that it appears as a hierearchical column

sat.set_index(['School Name', 'SAT Section']).unstack('SAT Section').Score

SAT Section                                         Math  Reading  Writing
School Name
A. Philip Randolph Campus High School                459      453      447
ACORN Community High School                          379      395      385
Abraham Lincoln High School                          441      422      422
Academy for Careers in Television and Film           444      458      444
Academy for College Preparation and Career Expl...   386      397      393
...                                                  ...      ...      ...
World Journalism Preparatory (College Board)         484      491      487
York Early College Academy                           496      481      473
Young Women's Leadership School                      478      465      472
Young Women's Leadership School in Astoria           483      464      477
Young Women's Leadership School in Queens            415      420      433

[375 rows x 3 columns]

In [8]:
#Alternative approach: using pivot method
pivoted = sat.pivot(index=['School Name'], columns='SAT Section', values='Score')

# Unpivoting DataFrame

In [9]:

pivoted.stack('SAT Section').reset_index()

                                     School Name SAT Section    0
0          A. Philip Randolph Campus High School        Math  459
1          A. Philip Randolph Campus High School     Reading  453
2          A. Philip Randolph Campus High School     Writing  447
3                    ACORN Community High School        Math  379
4                    ACORN Community High School     Reading  395
...                                          ...         ...  ...
1120  Young Women's Leadership School in Astoria     Reading  464
1121  Young Women's Leadership School in Astoria     Writing  477
1122   Young Women's Leadership School in Queens        Math  415
1123   Young Women's Leadership School in Queens     Reading  420
1124   Young Women's Leadership School in Queens     Writing  433

[1125 rows x 3 columns]

In [10]:
pivoted.head()

SAT Section                                         Math  Reading  Writing
School Name
A. Philip Randolph Campus High School                459      453      447
ACORN Community High School                          379      395      385
Abraham Lincoln High School                          441      422      422
Academy for Careers in Television and Film           444      458      444
Academy for College Preparation and Career Expl...   386      397      393

In [11]:
pivoted.reset_index().melt(id_vars=['School Name'],value_name='Score')

                                            School Name SAT Section  Score
0                 A. Philip Randolph Campus High School        Math    459
1                           ACORN Community High School        Math    379
2                           Abraham Lincoln High School        Math    441
3            Academy for Careers in Television and Film        Math    444
4     Academy for College Preparation and Career Exp...        Math    386
...                                                 ...         ...    ...
1120       World Journalism Preparatory (College Board)     Writing    487
1121                         York Early College Academy     Writing    473
1122                    Young Women's Leadership School     Writing    472
1123         Young Women's Leadership School in Astoria     Writing    477
1124          Young Women's Leadership School in Queens     Writing    433

[1125 rows x 3 columns]

# Aggregation in pivot using pivot_table() method

In [12]:
#Objective: Finding average SAT scores across Boroughs

In [13]:
sat.pivot_table(index='Borough', values=['Score'], aggfunc='mean')

                    Score
Borough
Bronx          400.908163
Brooklyn       410.085627
Manhattan      446.711610
Queens         448.492754
Staten Island  479.666667

In [14]:
#Objective: Finding min SAT scores across Boroughs

In [15]:
sat.pivot_table(index='Borough', values=['Score'], aggfunc='min')

               Score
Borough
Bronx            292
Brooklyn         284
Manhattan        316
Queens           318
Staten Island    409

In [16]:
sat.pivot_table(index='Borough', values=['Score'], aggfunc='sum', margins=True)

                Score
Borough
Bronx          117867
Brooklyn       134098
Manhattan      119272
Queens          92838
Staten Island   14390
All            478465

In [17]:
sat.pivot_table(index=['Borough', 'School Name'], columns=['SAT Section'],values=['Score'], aggfunc='sum',margins=True)

                                                                   Score  \
SAT Section                                                         Math
Borough       School Name
Bronx         Academy for Language and Technology                    371
              Academy for Scholarship and Entrepreneurship (C...     392
              Alfred E. Smith Career and Technical Education ...     390
              Antonia Pantoja Preparatory Academy (College Bo...     435
              Archimedes Academy for Math, Science, and Techn...     418
...                                                                  ...
Staten Island Ralph R. McKee Career and Technical Education H...     420
              Staten Island Technical High School                    711
              Susan E. Wagner High School                            496
              Tottenville High School                                494
All                                                               162354

                                                                          \
SAT Section                                                      Reading
Borough       School Name
Bronx         Academy for Language and Technology                    334
              Academy for Scholarship and Entrepreneurship (C...     408
              Alfred E. Smith Career and Technical Education ...     373
              Antonia Pantoja Preparatory Academy (College Bo...     415
              Archimedes Academy for Math, Science, and Techn...     430
...                                                                  ...
Staten Island Ralph R. McKee Career and Technical Education H...     429
              Staten Island Technical High School                    660
              Susan E. Wagner High School                            490
              Tottenville High School                                476
All                                                               159189

                                                                          \
SAT Section                                                      Writing
Borough       School Name
Bronx         Academy for Language and Technology                    348
              Academy for Scholarship and Entrepreneurship (C...     400
              Alfred E. Smith Career and Technical Education ...     371
              Antonia Pantoja Preparatory Academy (College Bo...     423
              Archimedes Academy for Math, Science, and Techn...     403
...                                                                  ...
Staten Island Ralph R. McKee Career and Technical Education H...     409
              Staten Island Technical High School                    670
              Susan E. Wagner High School                            487
              Tottenville High School                                476
All                                                               156922


SAT Section                                                          All
Borough       School Name
Bronx         Academy for Language and Technology                   1053
              Academy for Scholarship and Entrepreneurship (C...    1200
              Alfred E. Smith Career and Technical Education ...    1134
              Antonia Pantoja Preparatory Academy (College Bo...    1273
              Archimedes Academy for Math, Science, and Techn...    1251
...                                                                  ...
Staten Island Ralph R. McKee Career and Technical Education H...    1258
              Staten Island Technical High School                   2041
              Susan E. Wagner High School                           1473
              Tottenville High School                               1446
All                                                               478465

[376 rows x 4 columns]

In [18]:
sat.pivot_table(index=['Borough', 'School Name'], columns=['SAT Section'],values=['Score'], aggfunc=['min','max'],margins=True, margins_name='Grand Total')

                                                                   min  \
                                                                 Score
SAT Section                                                       Math
Borough       School Name
Bronx         Academy for Language and Technology                  371
              Academy for Scholarship and Entrepreneurship (C...   392
              Alfred E. Smith Career and Technical Education ...   390
              Antonia Pantoja Preparatory Academy (College Bo...   435
              Archimedes Academy for Math, Science, and Techn...   418
...                                                                ...
Staten Island Ralph R. McKee Career and Technical Education H...   420
              Staten Island Technical High School                  711
              Susan E. Wagner High School                          496
              Tottenville High School                              494
Grand Total                                                        317

                                                                          \

SAT Section                                                      Reading
Borough       School Name
Bronx         Academy for Language and Technology                    334
              Academy for Scholarship and Entrepreneurship (C...     408
              Alfred E. Smith Career and Technical Education ...     373
              Antonia Pantoja Preparatory Academy (College Bo...     415
              Archimedes Academy for Math, Science, and Techn...     430
...                                                                  ...
Staten Island Ralph R. McKee Career and Technical Education H...     429
              Staten Island Technical High School                    660
              Susan E. Wagner High School                            490
              Tottenville High School                                476
Grand Total                                                          302

                                                                          \

SAT Section                                                      Writing
Borough       School Name
Bronx         Academy for Language and Technology                    348
              Academy for Scholarship and Entrepreneurship (C...     400
              Alfred E. Smith Career and Technical Education ...     371
              Antonia Pantoja Preparatory Academy (College Bo...     423
              Archimedes Academy for Math, Science, and Techn...     403
...                                                                  ...
Staten Island Ralph R. McKee Career and Technical Education H...     409
              Staten Island Technical High School                    670
              Susan E. Wagner High School                            487
              Tottenville High School                                476
Grand Total                                                          284

                                                                              \

SAT Section                                                      Grand Total
Borough       School Name
Bronx         Academy for Language and Technology                        334
              Academy for Scholarship and Entrepreneurship (C...         392
              Alfred E. Smith Career and Technical Education ...         371
              Antonia Pantoja Preparatory Academy (College Bo...         415
              Archimedes Academy for Math, Science, and Techn...         403
...                                                                      ...
Staten Island Ralph R. McKee Career and Technical Education H...         409
              Staten Island Technical High School                        660
              Susan E. Wagner High School                                487
              Tottenville High School                                    476
Grand Total                                                              284

                                                                   max  \
                                                                 Score
SAT Section                                                       Math
Borough       School Name
Bronx         Academy for Language and Technology                  371
              Academy for Scholarship and Entrepreneurship (C...   392
              Alfred E. Smith Career and Technical Education ...   390
              Antonia Pantoja Preparatory Academy (College Bo...   435
              Archimedes Academy for Math, Science, and Techn...   418
...                                                                ...
Staten Island Ralph R. McKee Career and Technical Education H...   420
              Staten Island Technical High School                  711
              Susan E. Wagner High School                          496
              Tottenville High School                              494
Grand Total                                                        754

                                                                          \

SAT Section                                                      Reading
Borough       School Name
Bronx         Academy for Language and Technology                    334
              Academy for Scholarship and Entrepreneurship (C...     408
              Alfred E. Smith Career and Technical Education ...     373
              Antonia Pantoja Preparatory Academy (College Bo...     415
              Archimedes Academy for Math, Science, and Techn...     430
...                                                                  ...
Staten Island Ralph R. McKee Career and Technical Education H...     429
              Staten Island Technical High School                    660
              Susan E. Wagner High School                            490
              Tottenville High School                                476
Grand Total                                                          697

                                                                          \

SAT Section                                                      Writing
Borough       School Name
Bronx         Academy for Language and Technology                    348
              Academy for Scholarship and Entrepreneurship (C...     400
              Alfred E. Smith Career and Technical Education ...     371
              Antonia Pantoja Preparatory Academy (College Bo...     423
              Archimedes Academy for Math, Science, and Techn...     403
...                                                                  ...
Staten Island Ralph R. McKee Career and Technical Education H...     409
              Staten Island Technical High School                    670
              Susan E. Wagner High School                            487
              Tottenville High School                                476
Grand Total                                                          693



SAT Section                                                      Grand Total
Borough       School Name
Bronx         Academy for Language and Technology                        371
              Academy for Scholarship and Entrepreneurship (C...         408
              Alfred E. Smith Career and Technical Education ...         390
              Antonia Pantoja Preparatory Academy (College Bo...         435
              Archimedes Academy for Math, Science, and Techn...         430
...                                                                      ...
Staten Island Ralph R. McKee Career and Technical Education H...         429
              Staten Island Technical High School                        711
              Susan E. Wagner High School                                496
              Tottenville High School                                    494
Grand Total                                                              754

[376 rows x 8 columns]

# Skill Challenge

In [19]:
#Starting with main dataframe create a pivot table that summarizes the total student enrollment across all 5 boroughs.
#Which boroughs have the highest and lowest enrollment?

In [20]:
sat.head()

,School Name,Borough,Student Enrollment,Percent Tested,SAT Section,Score
0,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Math,459
1,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Reading,453
2,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Writing,447
3,Abraham Lincoln High School,Brooklyn,2341,54.9,Math,441
4,Abraham Lincoln High School,Brooklyn,2341,54.9,Reading,422

In [50]:
sat_pivot = sat.pivot_table(index='Borough', values=['Student Enrollment'], aggfunc='sum')

In [51]:
print('Largest Enrollment:\n', sat_pivot.nlargest(1,'Student Enrollment'))
print('Smalest Enrollment:\n', sat_pivot.nsmallest(1,'Student Enrollment') )

Largest Enrollment:
           Student Enrollment
Borough
Brooklyn              242814
Smalest Enrollment:
                Student Enrollment
Borough
Staten Island               55380

In [52]:
#Modify the pivot table from the above step to reflect the average student body size(Student enrollment) across boroughs in the same pivot table

In [56]:
sat_pivot = sat.pivot_table(index='Borough', values=['Student Enrollment'], aggfunc=['sum', 'mean'])

# Rename the columns
# sat_pivot.columns = ['Total Student Enrollment', 'Average Student Enrollment']

In [64]:
print(sat_pivot.columns)
sat_pivot.columns = [
    'Total Student Enrollment' if col == ('sum', 'Student Enrollment')
    else 'Average Student Enrollment' if col == ('mean', 'Student Enrollment')
    else f'{col[0]} {col[1]}'  # fallback if needed
    for col in sat_pivot.columns
]

MultiIndex([( 'sum', 'Student Enrollment'),
            ('mean', 'Student Enrollment')],
           )

In [65]:
sat_pivot

               Total Student Enrollment  Average Student Enrollment
Borough
Bronx                            159267                  541.724490
Brooklyn                         242814                  742.550459
Manhattan                        170370                  638.089888
Queens                           232437                 1122.884058
Staten Island                     55380                 1846.000000

In [66]:
#Create a pivot table of high schools from Queens, containing SAT section scores(SAT Section, scores) as columns and the School Name as index. Sort the table in order of math section scores.

In [74]:
sat[sat.Borough=='Queens'].\
pivot(index='School Name', columns='SAT Section', values='Score').\
sort_values(by='Math', ascending=False)

SAT Section                                         Math  Reading  Writing
School Name
Queens High School for the Sciences at York Col...   701      621      625
Townsend Harris High School                          680      640      661
Baccalaureate School for Global Education            633      620      628
Bard High School Early College Queens                631      598      610
Scholars' Academy                                    588      560      568
...                                                  ...      ...      ...
Middle College High School at LaGuardia Communi...   377      389      377
Queens High School for Information, Research, a...   372      362      352
August Martin High School                            366      372      364
Rockaway Park High School for Environmental Sus...   357      381      376
Pan American International High School               340      320      318

[69 rows x 3 columns]